### ISSUE TITLE
Tab GUI bug

### ISSUE THREAD

**Issue by GetShot** [DestinyNetwork/DungeonRealms-Bug-Report#143]
I was playing on another server (oc.tc) and for some reason when I logged onto this server and pressed tab, it showed the game I was just previously playing on another server...

http://prntscr.com/8ia8b0

**Comment by NeturonicAngelz** [comment]
This isn't an actual bug on the server, it's just due to Dungeon Realms not actually have a Tab Bar. So you could say it's an actual issue Minecraft Client Side.

If you were to log onto any server that doesn't have their Tab GUI setup, it would show the previous servers Tab.

Nevertheless, you can log out of Minecraft and back in to fix it ;>
