### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by SamColman13** [DestinyNetwork/DungeonRealms-Bug-Report#161]
Occasionally I will spawn in Shard 3 around jagged rocks and I will get my items, the start up messages will appear, but there will be no blocks and no mobs I will just be in space, not taking damage just sitting there

**Comment by NeturonicAngelz** [comment]
This seems like a Visual / Lag glitch that can occur whenever the servers threads are running higher than what they are supposed to. For example:

- Whenever you log onto a server and it can't send any information due to lag, you will receive a blank world since it hasn't been able to download the information to you.
